version: '3.8'
services:
  webhookd:
    restart: always
    container_name: webhookd
    image: raiyni/webhookd:edge
    volumes:
      - '/var/opt/webhookd/:/var/opt/webhookd/'
      - '/etc/ssmtp/ssmtp.conf:/etc/ssmtp/ssmtp.conf'
    ports:
      - '8000:8080'
    environment:
      - WHD_PASSWD_FILE=/var/opt/webhookd/.htpasswd
    command: ['webhookd', '--scripts', '/var/opt/webhookd/scripts']