version: '3.8'
services:
  webhookd:
    restart: always
    container_name: webhookd
    image: raiyni/webhookd:edge
    volumes:
      - '/var/opt/webhookd/:/var/opt/webhookd/'
      - '/etc/ssmtp/ssmtp.conf:/etc/ssmtp/ssmtp.conf'
    ports:
      - '127.0.0.1:8000:8080'
    command: ['webhookd', '--scripts', '/var/opt/webhookd/scripts']